import type { Locale } from "@/i18n/config";
import type { Article } from "@/lib/articles";

export const articleUi: Record<Locale, { journal: string; heading: string; intro: string; read: string; related: string; tips: string; cta: string; ctaText: string; ctaButton: string }> = {
  id: { journal: "Om Bram Journal", heading: "Panduan perjalanan Bandung", intro: "Riset destinasi, itinerary, dan tips praktis untuk membantu Anda merencanakan perjalanan yang lebih nyaman.", read: "Baca artikel", related: "Artikel terkait", tips: "Catatan perjalanan", cta: "Siap menyusun rute Bandung?", ctaText: "Pilih paket berdasarkan destinasi, harga, dan kendaraan yang paling sesuai.", ctaButton: "Lihat paket tour" },
  en: { journal: "Om Bram Journal", heading: "Bandung travel guides", intro: "Destination research, itineraries, and practical tips for planning a more comfortable journey.", read: "Read article", related: "Related articles", tips: "Travel notes", cta: "Ready to plan your Bandung route?", ctaText: "Choose a package based on destinations, price, and the right vehicle.", ctaButton: "View tour packages" },
  zh: { journal: "Om Bram 旅行日志", heading: "万隆旅行指南", intro: "目的地研究、行程建议和实用技巧，帮助您规划更舒适的旅程。", read: "阅读文章", related: "相关文章", tips: "旅行提示", cta: "准备规划万隆路线了吗？", ctaText: "根据目的地、价格和合适的车辆选择套餐。", ctaButton: "查看旅游套餐" },
  ms: { journal: "Jurnal Om Bram", heading: "Panduan perjalanan Bandung", intro: "Kajian destinasi, itinerari dan tip praktikal untuk perjalanan yang lebih selesa.", read: "Baca artikel", related: "Artikel berkaitan", tips: "Nota perjalanan", cta: "Sedia merancang laluan Bandung?", ctaText: "Pilih pakej berdasarkan destinasi, harga dan kenderaan yang sesuai.", ctaButton: "Lihat pakej lawatan" },
  th: { journal: "บันทึก Om Bram", heading: "คู่มือท่องเที่ยวบันดุง", intro: "ข้อมูลสถานที่ แผนการเดินทาง และเคล็ดลับเพื่อการเดินทางที่สะดวกสบายยิ่งขึ้น", read: "อ่านบทความ", related: "บทความที่เกี่ยวข้อง", tips: "เคล็ดลับการเดินทาง", cta: "พร้อมวางแผนเส้นทางบันดุงหรือยัง", ctaText: "เลือกแพ็กเกจตามสถานที่ ราคา และรถที่เหมาะสม", ctaButton: "ดูแพ็กเกจทัวร์" },
  ta: { journal: "Om Bram பயணக் குறிப்புகள்", heading: "பாண்டுங் பயண வழிகாட்டி", intro: "உங்கள் பயணத்தை வசதியாக திட்டமிட இடங்கள், பயணத்திட்டங்கள் மற்றும் நடைமுறை குறிப்புகள்.", read: "கட்டுரையைப் படிக்க", related: "தொடர்புடைய கட்டுரைகள்", tips: "பயணக் குறிப்புகள்", cta: "பாண்டுங் பாதையைத் திட்டமிட தயாரா?", ctaText: "இடம், விலை மற்றும் பொருத்தமான வாகனத்தின் அடிப்படையில் தொகுப்பைத் தேர்வுசெய்யுங்கள்.", ctaButton: "சுற்றுலா தொகுப்புகளைப் பார்க்க" },
  ja: { journal: "Om Bram ジャーナル", heading: "バンドン旅行ガイド", intro: "目的地情報、旅程、実用的なヒントで快適な旅行を計画しましょう。", read: "記事を読む", related: "関連記事", tips: "旅行メモ", cta: "バンドンのルートを計画しませんか？", ctaText: "目的地、料金、最適な車両からプランを選べます。", ctaButton: "ツアープランを見る" },
  ko: { journal: "Om Bram 여행 저널", heading: "반둥 여행 가이드", intro: "더 편안한 여행을 위한 목적지 정보, 일정 및 실용적인 팁입니다.", read: "기사 읽기", related: "관련 기사", tips: "여행 메모", cta: "반둥 여행 경로를 계획할 준비가 되셨나요?", ctaText: "목적지, 가격, 차량을 기준으로 패키지를 선택하세요.", ctaButton: "투어 패키지 보기" },
  ar: { journal: "مجلة Om Bram", heading: "دليل السفر إلى باندونغ", intro: "معلومات عن الوجهات ومسارات السفر ونصائح عملية لتخطيط رحلة مريحة.", read: "اقرأ المقال", related: "مقالات ذات صلة", tips: "ملاحظات السفر", cta: "هل أنت مستعد لتخطيط مسار باندونغ؟", ctaText: "اختر الباقة حسب الوجهات والسعر والمركبة المناسبة.", ctaButton: "عرض باقات الرحلات" }
};

const bodyTemplates: Record<Locale, { paragraphs: (article: Article) => string[]; tips: string[] }> = {
  id: { paragraphs: (article) => article.paragraphs, tips: [] },
  en: { paragraphs: (article) => [`This guide focuses on ${article.title}. Start by checking the route, opening hours, and travel time before leaving.`, `Group nearby destinations together so you spend more time enjoying Bandung and less time on the road. A private driver also makes it easier to adjust the itinerary when traffic or weather changes.`, `Choose a vehicle based on the number of passengers, luggage, and road conditions. Confirm the pickup point and the total package details before booking.`], tips: ["Check opening hours before departure.", "Group destinations by direction.", "Choose a vehicle that fits your group and luggage."] },
  zh: { paragraphs: (article) => [`本指南介绍${article.title}。出发前请确认路线、开放时间和预计车程。`, `将相近的景点安排在同一条路线中，可以减少路上时间，更充分地享受万隆。私人司机也能在交通或天气变化时灵活调整行程。`, `请根据人数、行李和道路情况选择车辆。预订前确认接送地点和套餐总费用。`], tips: ["出发前确认开放时间。", "按方向安排景点。", "选择适合人数和行李的车辆。"] },
  ms: { paragraphs: (article) => [`Panduan ini memfokuskan ${article.title}. Semak laluan, waktu operasi dan anggaran masa perjalanan sebelum bertolak.`, `Gabungkan destinasi yang berdekatan supaya lebih banyak masa dapat digunakan untuk menikmati Bandung. Pemandu persendirian memudahkan perubahan jadual apabila trafik atau cuaca berubah.`, `Pilih kenderaan berdasarkan jumlah penumpang, bagasi dan keadaan jalan. Sahkan tempat jemput dan jumlah pakej sebelum membuat tempahan.`], tips: ["Semak waktu operasi sebelum bertolak.", "Susun destinasi mengikut arah.", "Pilih kenderaan mengikut kumpulan dan bagasi."] },
  th: { paragraphs: (article) => [`คู่มือนี้แนะนำ ${article.title} โปรดตรวจสอบเส้นทาง เวลาเปิดทำการ และเวลาเดินทางก่อนออกเดินทาง`, `จัดสถานที่ใกล้กันไว้ในเส้นทางเดียวกัน เพื่อใช้เวลาเที่ยวบันดุงได้มากขึ้น การมีคนขับส่วนตัวยังช่วยปรับแผนเมื่อการจราจรหรือสภาพอากาศเปลี่ยนแปลง`, `เลือกยานพาหนะให้เหมาะกับจำนวนผู้โดยสาร สัมภาระ และสภาพถนน ตรวจสอบจุดรับและรายละเอียดค่าใช้จ่ายก่อนจอง`], tips: ["ตรวจสอบเวลาเปิดทำการก่อนเดินทาง", "จัดสถานที่ตามทิศทาง", "เลือกรถให้เหมาะกับกลุ่มและสัมภาระ"] },
  ta: { paragraphs: (article) => [`இந்த வழிகாட்டி ${article.title} பற்றியது. புறப்படுவதற்கு முன் பாதை, திறக்கும் நேரம் மற்றும் பயண நேரத்தைச் சரிபார்க்கவும்.`, `அருகிலுள்ள இடங்களை ஒரே பாதையில் சேர்த்தால் பாண்டுங்கை ரசிக்க அதிக நேரம் கிடைக்கும். போக்குவரத்து அல்லது வானிலை மாறும்போது தனியார் ஓட்டுநர் திட்டத்தை மாற்ற உதவுவார்.`, `பயணிகள், சாமான்கள் மற்றும் சாலை நிலைக்கு ஏற்ற வாகனத்தைத் தேர்ந்தெடுக்கவும். முன்பதிவுக்கு முன் pickup இடம் மற்றும் மொத்த கட்டணத்தை உறுதிப்படுத்தவும்.`], tips: ["புறப்படுவதற்கு முன் திறக்கும் நேரத்தைச் சரிபார்க்கவும்.", "இடங்களை திசைப்படி அமைக்கவும்.", "குழு மற்றும் சாமான்களுக்கு ஏற்ற வாகனத்தைத் தேர்வுசெய்யவும்."] },
  ja: { paragraphs: (article) => [`このガイドでは${article.title}をご紹介します。出発前にルート、営業時間、所要時間を確認しましょう。`, `近い観光地を同じルートにまとめると、移動時間を減らしてバンドンをより楽しめます。専用ドライバーなら交通や天候に合わせて予定を調整できます。`, `人数、荷物、道路状況に合う車両を選びましょう。予約前に送迎場所と料金の総額を確認してください。`], tips: ["出発前に営業時間を確認する。", "観光地を方向別にまとめる。", "人数と荷物に合う車両を選ぶ。"] },
  ko: { paragraphs: (article) => [`이 가이드는 ${article.title}을(를) 소개합니다. 출발 전에 경로, 운영 시간과 이동 시간을 확인하세요.`, `가까운 목적지를 한 경로로 묶으면 이동 시간을 줄이고 반둥을 더 여유롭게 즐길 수 있습니다. 전용 운전기사가 있으면 교통과 날씨에 따라 일정을 조정하기도 쉽습니다.`, `인원, 수하물과 도로 상황에 맞는 차량을 선택하세요. 예약 전에 픽업 장소와 총 요금을 확인하시기 바랍니다.`], tips: ["출발 전 운영 시간을 확인하세요.", "목적지를 방향별로 묶으세요.", "그룹과 수하물에 맞는 차량을 선택하세요."] },
  ar: { paragraphs: (article) => [`يقدم هذا الدليل معلومات عن ${article.title}. تحقق من المسار وساعات العمل ووقت الرحلة قبل الانطلاق.`, `اجمع الوجهات القريبة في مسار واحد لتقضي وقتاً أطول في الاستمتاع بباندونغ. يساعدك السائق الخاص على تعديل الخطة عند تغير حركة المرور أو الطقس.`, `اختر المركبة حسب عدد المسافرين والأمتعة وحالة الطريق. تأكد من نقطة الالتقاء والتكلفة الإجمالية قبل الحجز.`], tips: ["تحقق من ساعات العمل قبل المغادرة.", "رتب الوجهات حسب الاتجاه.", "اختر مركبة تناسب المجموعة والأمتعة."] }
};

export function getLocalizedArticle(article: Article, locale: string): Article {
  const selectedLocale = (Object.prototype.hasOwnProperty.call(bodyTemplates, locale) ? locale : "id") as Locale;
  const template = bodyTemplates[selectedLocale];
  return { ...article, paragraphs: template.paragraphs(article), tips: selectedLocale === "id" ? article.tips : template.tips };
}
