import type { Locale } from "@/i18n/config";

export const articleUi: Record<Locale, { journal: string; heading: string; intro: string; read: string; related: string; tips: string; cta: string; ctaText: string; ctaButton: string }> = {
  id: { journal: "Om Bram Journal", heading: "Panduan perjalanan Bandung", intro: "Riset destinasi, itinerary, dan tips praktis untuk membantu Anda merencanakan perjalanan yang lebih nyaman.", read: "Baca artikel", related: "Artikel terkait", tips: "Catatan perjalanan", cta: "Siap menyusun rute Bandung?", ctaText: "Pilih paket berdasarkan destinasi, harga, dan kendaraan yang paling sesuai.", ctaButton: "Lihat paket tour" },
  en: { journal: "Om Bram Journal", heading: "Bandung travel guides", intro: "Destination research, itineraries, and practical tips for planning a more comfortable journey.", read: "Read article", related: "Related articles", tips: "Travel notes", cta: "Ready to plan your Bandung route?", ctaText: "Choose a package based on destinations, price, and the right vehicle.", ctaButton: "View tour packages" },
  zh: { journal: "Om Bram 旅行日志", heading: "万隆旅行指南", intro: "目的地研究、行程建议和实用技巧，帮助您规划更舒适的旅程。", read: "阅读文章", related: "相关文章", tips: "旅行提示", cta: "准备规划万隆路线了吗？", ctaText: "根据目的地、价格和合适的车辆选择套餐。", ctaButton: "查看旅游套餐" },
  ms: { journal: "Jurnal Om Bram", heading: "Panduan perjalanan Bandung", intro: "Kajian destinasi, itinerari dan tip praktikal untuk perjalanan yang lebih selesa.", read: "Baca artikel", related: "Artikel berkaitan", tips: "Nota perjalanan", cta: "Sedia merancang laluan Bandung?", ctaText: "Pilih pakej berdasarkan destinasi, harga dan kenderaan yang sesuai.", ctaButton: "Lihat pakej lawatan" },
  th: { journal: "บันทึก Om Bram", heading: "คู่มือท่องเที่ยวบันดุง", intro: "ข้อมูลสถานที่ แผนการเดินทาง และเคล็ดลับเพื่อการเดินทางที่สะดวกสบายยิ่งขึ้น", read: "อ่านบทความ", related: "บทความที่เกี่ยวข้อง", tips: "เคล็ดลับการเดินทาง", cta: "พร้อมวางแผนเส้นทางบันดุงหรือยัง", ctaText: "เลือกแพ็กเกจตามสถานที่ ราคา และรถที่เหมาะสม", ctaButton: "ดูแพ็กเกจทัวร์" },
  ta: { journal: "Om Bram பயணக் குறிப்புகள்", heading: "பாண்டுங் பயண வழிகாட்டி", intro: "உங்கள் பயணத்தை வசதியாக திட்டமிட இடங்கள், பயணத்திட்டங்கள் மற்றும் நடைமுறை குறிப்புகள்.", read: "கட்டுரையைப் படிக்க", related: "தொடர்புடைய கட்டுரைகள்", tips: "பயணக் குறிப்புகள்", cta: "பாண்டுங் பாதையைத் திட்டமிட தயாரா?", ctaText: "இடம், விலை மற்றும் பொருத்தமான வாகனத்தின் அடிப்படையில் தொகுப்பைத் தேர்வுசெய்யுங்கள்.", ctaButton: "சுற்றுலா தொகுப்புகளைப் பார்க்க" },
  ja: { journal: "Om Bram ジャーナル", heading: "バンドン旅行ガイド", intro: "目的地情報、旅程、実用的なヒントで快適な旅行を計画しましょう。", read: "記事を読む", related: "関連記事", tips: "旅行メモ", cta: "バンドンのルートを計画しませんか？", ctaText: "目的地、料金、最適な車両からプランを選べます。", ctaButton: "ツアープランを見る" },
  ko: { journal: "Om Bram 여행 저널", heading: "반둥 여행 가이드", intro: "더 편안한 여행을 위한 목적지 정보, 일정 및 실용적인 팁입니다.", read: "기사 읽기", related: "관련 기사", tips: "여행 메모", cta: "반둥 여행 경로를 계획할 준비가 되셨나요?", ctaText: "목적지, 가격, 차량을 기준으로 패키지를 선택하세요.", ctaButton: "투어 패키지 보기" },
  ar: { journal: "مجلة Om Bram", heading: "دليل السفر إلى باندونغ", intro: "معلومات عن الوجهات ومسارات السفر ونصائح عملية لتخطيط رحلة مريحة.", read: "اقرأ المقال", related: "مقالات ذات صلة", tips: "ملاحظات السفر", cta: "هل أنت مستعد لتخطيط مسار باندونغ؟", ctaText: "اختر الباقة حسب الوجهات والسعر والمركبة المناسبة.", ctaButton: "عرض باقات الرحلات" }
};
